baseURL = 'https://你的用户名.github.io/'
languageCode = 'zh-cn'
title = 'My Archive'
theme = 'hugo-book' # 这里的名称必须和上面脚本里克隆的文件夹名一致

[params]
  BookTheme = 'dark'
  BookFontFamily = '"SF Pro Local", -apple-system, sans-serif'
