baseURL = 'https://onweb1atk.github.io/new-blog/'
languageCode = 'zh-cn'
title = "1atk's archive"
theme = 'hugo-book'

[params]
  BookCustomStyle = 'css/custom.css'
  BookTheme = 'dark'
  BookMenuBundle = false
  BookCustomJS = "js/egg.js"
