baseURL = 'https://onweb1atk.github.io/new-blog/'
languageCode = 'zh-cn'
title = "1atk's archive"
theme = 'hugo-book'
buildFuture = true
buildDrafts = true

[markup.goldmark.renderer]
  hardWraps = true

[params]
  BookCustomStyle = 'css/custom.css'
  BookTheme = 'dark'
  BookMenuBundle = false
  # 必须是这样，对应 static/js/egg.js
  BookCustomJS = "js/egg.js"
